# -*- coding: utf-8 -*-
"""ResNet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgoOdLKx1QE1y-37nURJGW53MXOaPies
"""

import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras import layers, models
from tensorflow.keras.layers import Dense

train_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255,
    zoom_range=0.2,
    horizontal_flip=True
)

val_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255
)

test_datagen = tf.keras.preprocessing.image.ImageDataGenerator(
    rescale=1./255
)

train_data = train_datagen.flow_from_directory(
    '/content/drive/MyDrive/CKD_split/train',
    target_size=(256, 256),
    batch_size=32
)

val_data = val_datagen.flow_from_directory(
    '/content/drive/MyDrive/CKD_split/val',
    target_size=(256, 256),
    batch_size=32
)

test_data = test_datagen.flow_from_directory(
    '/content/drive/MyDrive/CKD_split/test',
    target_size=(256, 256),
    batch_size=32
)

num_classes = train_data.num_classes
nb_train_samples = train_data.samples
nb_val_samples = val_data.samples

def Resnet50_model_finetuning(freeze_baselayers):
    base_model = tf.keras.applications.resnet50.ResNet50(
        include_top=False,
        weights='imagenet',
        input_tensor=None,
        input_shape=(256, 256, 3),
        classes=5  # Change this to the number of classes in your dataset
    )

    # Freeze base model layers if specified
    if freeze_baselayers:
        base_model.trainable = False

    # Building the new classification layers on top of the base model
    input = base_model.inputs
    mod = base_model.output
    mod = tf.keras.layers.Flatten()(mod)
    mod = Dense(64, activation="relu")(mod)
    mod = Dense(64, activation="relu")(mod)
    output = Dense(num_classes, activation='softmax')(mod)

    # Creating the new model
    new_model = tf.keras.Model(inputs=input, outputs=output)
    return new_model

model = Resnet50_model_finetuning(freeze_baselayers=True)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=tf.keras.losses.CategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

history = model.fit(train_data, epochs=10, validation_data=val_data)

plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])
plt.title("Model Accuracy")
plt.ylabel("accuracy")
plt.xlabel("epochs")
plt.legend(["train", "test"], loc="upper left")
plt.show()

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])
plt.title("Model Loss")
plt.ylabel("loss")
plt.xlabel("epochs")
plt.legend(["train", "test"], loc="upper left")
plt.show()

results = model.evaluate(test_data, verbose=0)
print("Loss: {:.5f}".format(results[0]))
print("Accuracy: {:.2f}%".format(results[1] * 100))













import os
import shutil
import random

# SOURCE DATASET PATH
source_dir = '/content/drive/MyDrive/CKDupdated'

# DESTINATION PATH
base_dir = '/content/drive/MyDrive/CKD_split'
train_dir = os.path.join(base_dir, 'train')
val_dir = os.path.join(base_dir, 'val')
test_dir = os.path.join(base_dir, 'test')

# Create directories
for folder in [train_dir, val_dir, test_dir]:
    os.makedirs(folder, exist_ok=True)

# Split ratios
train_ratio = 0.7
val_ratio = 0.15
test_ratio = 0.15

# Loop through each class
for class_name in os.listdir(source_dir):
    class_path = os.path.join(source_dir, class_name)

    if not os.path.isdir(class_path):
        continue

    images = os.listdir(class_path)
    random.shuffle(images)

    total_images = len(images)
    train_end = int(train_ratio * total_images)
    val_end = train_end + int(val_ratio * total_images)

    splits = {
        train_dir: images[:train_end],
        val_dir: images[train_end:val_end],
        test_dir: images[val_end:]
    }

    for split_dir, split_images in splits.items():
        class_split_dir = os.path.join(split_dir, class_name)
        os.makedirs(class_split_dir, exist_ok=True)

        for img in split_images:
            src = os.path.join(class_path, img)
            dst = os.path.join(class_split_dir, img)
            shutil.copy(src, dst)

print("✅ Dataset successfully split into Train / Val / Test")

